name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubutu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Code vulnerability scanning
        uses: anchors/scan-action@v3
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      #- name: Upload vulnerability report
      #  uses: github/codeql-action/updolad-sarif@v2
      #  if: sucess() || failure()
      #  with:
      #    sarif-file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          chmod +x mvnw
          ./mvnw clean install
